ARG BUILD_TAG
FROM simple_elastic_language_sel_server:${BUILD_TAG}

ARG PROJECT
ENV PROJECT="${PROJECT}"

# Run pip3 install to install our packages for test purpose
ADD projects/${PROJECT}/setup.py .
ADD projects/${PROJECT}/setup.cfg .
RUN pip3 install -e '.[test]' \
  && rm setup.py setup.cfg

ADD scripts/ /scripts
ADD projects/${PROJECT}/tests /tests
