version: '2.4'
services:

  server:
    image: simple_elastic_language_sel_server:${BUILD_TAG}
    environment:
      - "ES_HOST=http://elasticsearch"
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "9000:9000"

  elasticsearch:
    image: elasticsearch:2.4
    command: elasticsearch -Des.nodes.discovery=false
    environment:
      - "ES_HEAP_SIZE=8G"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

